using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace FirstExercise
{
    public partial class EatingForm : Form
    {
        public EatingForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = Stats.boughtFood;
        }

        private void eatButtonClick(object sender, EventArgs e)
        {
            var boughtFood = Stats.boughtFood;
            bool doesProductExist = false;
            foreach (Food f in boughtFood)
            {
                if (f.name == foodNameEdit.Text)
                {
                    doesProductExist = true;
                    Stats.EnergyLevel += f.energy;
                    Stats.HungerPercentage =  (Stats.EnergyNeeded - Stats.EnergyLevel) / Stats.EnergyNeeded * 100;
                    boughtFood.removeProduct(f, 1);
                    
                    Form1.instance.updateStats();
                    this.Close();
                    return;
                    
                }
            }
            if (!doesProductExist) MessageBox.Show("The product does not exist!");
        }
    }
}
